name: Publish

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Clone events directory
        run: mkdir events && cd events && cp -r ../.git . && git pull && git checkout events && cd ..
      - name: Run main.py
        run: python main.py
        env: # Set the secret as an input
          MEETUP_KEY: ${{ secrets.MEETUP_KEY }}
          MEETUP_SECRET: ${{ secrets.MEETUP_SECRET }}
      - name: Push events directory
        run: cd events && git config --global user.name "Python ES" && git config --global user.email "contacto@es.python.org" && git commit -am "Updated events." && git push && cd ..
